apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-test-index
  namespace: argo-test
data:
  index.html: |-
    <!doctype html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Staging</title>
    </head>
    <body>
      <h1>Hello from argo-test (staging)!</h1>
      <p>Environment: Staging</p>
    </body>
    </html>
