apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-test-index
data:
  index.html: |-
    <!doctype html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Hello</title>
    </head>
    <body>
      <h1>Hello from argo-test (base)!</h1>
      <p>This is the base index; overlays will patch this.</p>
    </body>
    </html>
